// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwRi4le-Tlrli3At1UWsRpo4PUkhIrycY',
    appId: '1:581725088932:web:b63e03fa5cf878f5e9ca31',
    messagingSenderId: '581725088932',
    projectId: 'restaurant-flutter-64233',
    authDomain: 'restaurant-flutter-64233.firebaseapp.com',
    storageBucket: 'restaurant-flutter-64233.firebasestorage.app',
    measurementId: 'G-JKL2QGVLWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOf90XVSlTWuK-bUdwRI_-MjBRg8XYmlk',
    appId: '1:581725088932:android:b5159b58a7fdb2c9e9ca31',
    messagingSenderId: '581725088932',
    projectId: 'restaurant-flutter-64233',
    storageBucket: 'restaurant-flutter-64233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvLWRe7h2t7Mbaj2C7mURBEYbStV-Kv-o',
    appId: '1:581725088932:ios:1f86364da4fd592be9ca31',
    messagingSenderId: '581725088932',
    projectId: 'restaurant-flutter-64233',
    storageBucket: 'restaurant-flutter-64233.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvLWRe7h2t7Mbaj2C7mURBEYbStV-Kv-o',
    appId: '1:581725088932:ios:1f86364da4fd592be9ca31',
    messagingSenderId: '581725088932',
    projectId: 'restaurant-flutter-64233',
    storageBucket: 'restaurant-flutter-64233.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwRi4le-Tlrli3At1UWsRpo4PUkhIrycY',
    appId: '1:581725088932:web:51676549d7cab68fe9ca31',
    messagingSenderId: '581725088932',
    projectId: 'restaurant-flutter-64233',
    authDomain: 'restaurant-flutter-64233.firebaseapp.com',
    storageBucket: 'restaurant-flutter-64233.firebasestorage.app',
    measurementId: 'G-F1NRVXV9KH',
  );
}
